#!/usr/bin/env python3
"""Write docs/prompt.md, the document that shows how the brief's content is produced, from the prompt sources.

usage: prompt_doc.py [--check]

The prompts are built by run.py's `build_prompts` with the `brief` variant from this folder, an invented pull request
and an invented repository context, so the document holds the real rules, the real answer shape and the real prompt
layout. `--check` writes nothing and exits 1 when docs/prompt.md differs from what this program would write.
"""
import argparse
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

from run import build_prompts

ROOT: Path = Path(__file__).resolve().parent
DOC: Path = ROOT / "docs" / "prompt.md"
VARIANT: Path = ROOT / "variants" / "brief.toml"

PR: dict[str, Any] = {
    "title": "Add a nickname to the profile page",
    "body": "",
    "headRefName": "nickname",
    "commits": [
        {"messageHeadline": "Accept a nickname in the profile route"},
        {"messageHeadline": "Store the nickname with the profile"},
    ],
}

DIFF = """diff --git a/src/repositories/profileRepository.ts b/src/repositories/profileRepository.ts
--- a/src/repositories/profileRepository.ts
+++ b/src/repositories/profileRepository.ts
@@ -10,6 +10,6 @@ export async function updateProfile(db: Db, id: string, input: ProfileInput) {
   return db.one(
-    "UPDATE profiles SET display_name = $1 WHERE id = $2 RETURNING *",
-    [input.displayName, id],
+    "UPDATE profiles SET display_name = $1, nickname = $2 WHERE id = $3 RETURNING *",
+    [input.displayName, input.nickname, id],
   );
 }
diff --git a/src/routes/profile.ts b/src/routes/profile.ts
--- a/src/routes/profile.ts
+++ b/src/routes/profile.ts
@@ -21,6 +21,6 @@ router.patch("/profile", async (req, res) => {
-  const { displayName } = req.body;
-  const profile = await updateProfile(db, req.user.id, { displayName });
+  const { displayName, nickname } = req.body;
+  const profile = await updateProfile(db, req.user.id, { displayName, nickname });
   res.json(profile);
 });
"""

# The shape of what context_pack.py emits: a section with nothing to list is left out, so there is no migrations section.
CONTEXT = """### Callers
Confirmed callers of changed code, from the base commit. The list is partial: every file listed really calls the code, but many callers are missing (for example calls over HTTP, through interfaces or by reflection).
- `updateProfile`: 2 caller files: src/jobs/syncProfiles.ts, src/routes/admin.ts

### App reach
Apps that contain changed files or files that call the changed code.
- API: 2 changed files, 2 caller files

### API contract changes
Differences between the base and head `api/openapi.json`.
- UpdateProfileRequest.nickname (now required)"""

INTRO = """\
<!-- Generated by prompt_doc.py from the prompt sources. Edit those, then run `python prompt_doc.py`. -->
# How the brief is written

Each brief comes from two prompts sent to the model: one system prompt and one user prompt per pull request. The
system prompt says what to write: the rules, the shape of the answer and the repository context. The user prompt is
the pull request itself: its title, branch, commits and diff. The model replies with a YAML answer, and `render.py`
turns that into the brief.

The system prompt has three sources: PR-Agent's `/describe` template (`vendor/pr_description_prompts.toml`), the
variant file (`variants/brief.toml`), which adds the rules and two answer fields to that template, and the repository
context that `context_pack.py` builds from the repository. `run.py <pr> --prompt-only` prints the real prompts for any
pull request. The sections below show them for an invented pull request.

![How the prompt is assembled](prompt-assembly.svg)"""


def fenced(text: str, language: str = "") -> str:
    """`text` in a code fence long enough that no backtick run inside it ends the fence early."""
    longest: int = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence: str = "`" * max(3, longest + 1)
    return f"{fence}{language}\n{text}\n{fence}"


def build() -> str:
    variant: dict[str, Any] = tomllib.loads(VARIANT.read_text())
    system, user = build_prompts(variant, PR, DIFF, False, CONTEXT)
    rules: str = variant["extra_instructions"].strip("\n")
    shape_start: int = system.index("class PRType")
    shape: str = system[shape_start:system.index("\n=====", shape_start)].strip("\n")
    context: str = re.search(r"Repository context:\n=====\n(.*?)\n=====\n", system, re.DOTALL).group(1)
    about_context: str = re.search(r"^The Repository context section lists[^\n]*?\.(?= )", rules, re.MULTILINE).group(0)
    partial: str = re.search(r"The caller list is partial:[^\n]*?\.(?=\s|$)", rules).group(0)
    return "\n\n".join([
        INTRO,
        "## The brief's rules\n\n" + fenced(rules),
        "## The answer's shape\n\n" + fenced(shape, "python"),
        f"## Repository context\n\n{about_context}\n{partial}\n\n" + fenced(context),
        "## The user prompt\n\n" + fenced(user.strip("\n")),
        "## The full system prompt\n\n<details><summary>Full system prompt for the example PR</summary>\n\n"
        + fenced(system.strip("\n")) + "\n\n</details>",
    ]) + "\n"


def main(argv: list[str] | None = None, doc: Path = DOC) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 when the document on disk is stale")
    args = parser.parse_args(argv)
    text: str = build()
    if args.check:
        if not doc.exists() or doc.read_text() != text:
            print(f"{doc.name} is stale: run `python prompt_doc.py` and commit it", file=sys.stderr)
            return 1
        return 0
    doc.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
